// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgPSthfy_8gkEzv2y10y-lM9_n2gQHE78',
    appId: '1:218295407191:web:29eeb0fc3f3668c9b68912',
    messagingSenderId: '218295407191',
    projectId: 'finalprojectlntcamp',
    authDomain: 'finalprojectlntcamp.firebaseapp.com',
    storageBucket: 'finalprojectlntcamp.appspot.com',
    measurementId: 'G-TYEHVT0086',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkjYUTdj5aYeIoxA6NHgRGSESwfwVly0E',
    appId: '1:218295407191:android:ffc4a9565d30c12eb68912',
    messagingSenderId: '218295407191',
    projectId: 'finalprojectlntcamp',
    storageBucket: 'finalprojectlntcamp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrSXKhex-f1c82-rfJhl8lZ7o03zDoCio',
    appId: '1:218295407191:ios:30006102f03d091eb68912',
    messagingSenderId: '218295407191',
    projectId: 'finalprojectlntcamp',
    storageBucket: 'finalprojectlntcamp.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrSXKhex-f1c82-rfJhl8lZ7o03zDoCio',
    appId: '1:218295407191:ios:30006102f03d091eb68912',
    messagingSenderId: '218295407191',
    projectId: 'finalprojectlntcamp',
    storageBucket: 'finalprojectlntcamp.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgPSthfy_8gkEzv2y10y-lM9_n2gQHE78',
    appId: '1:218295407191:web:8d93c34d54340a19b68912',
    messagingSenderId: '218295407191',
    projectId: 'finalprojectlntcamp',
    authDomain: 'finalprojectlntcamp.firebaseapp.com',
    storageBucket: 'finalprojectlntcamp.appspot.com',
    measurementId: 'G-P30GDQZ921',
  );
}
